vich_uploader:
    db_driver: orm

    mappings:
        products:
            uri_prefix: /img/upload
            upload_destination: '%kernel.project_dir%/public/img/upload'

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
